---
title: "Test Code"
output: html_document
date: "2026-01-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Canonical Variate Analysis
```{r}
?lda()

library(MASS)
library (dplyr)




lm_cva <- subset_lm %>% 
  dplyr::select(c(2:19, 21))

write.csv(lm_cva, file = "data/LM_CVA.csv")


cva <- lda(Genus ~ . , data = lm_cva)


cva2 <- 
  lm_cva %>% 
  dplyr::select(-Genus) %>% # drop Species column 
  as.matrix  # cast to matrix for calculations

# calculate CV scGenus# calculate CV scores
CVA.scores <- cva2 %*% cva$scaling

# create data frame with scores
CV.df <- data.frame(CVA.scores)
CV.df$Genus <- lm_cva$Genus

cva.plot <-
  ggplot(CV.df, aes(x = LD1, y = LD2)) + 
  geom_point(aes(color=Genus), alpha=0.5) + 
  labs(x = "CV1", y = "CV2") +
  coord_fixed(ratio=1)  # keep the unit scaling of the plot fixed at 1

cva.plot

```

```{r}
chi2 = qchisq(0.05,2, lower.tail=FALSE)

CIregions.mean.and.pop <-
  CV.df %>%
  group_by(Genus) %>%
  summarize(CV1.mean = mean(LD1),
            CV2.mean = mean(LD2),
            mean.radii = sqrt(chi2/n()),
            popn.radii = sqrt(chi2))

library(ggforce) #Draw circles

cva.plot2 <-
  cva.plot + 
  geom_circle(data = CIregions.mean.and.pop,
              mapping = aes(x0 = CV1.mean, y0 = CV2.mean, r = mean.radii, color = Genus),
              inherit.aes = FALSE) +
  geom_circle(data = CIregions.mean.and.pop,
              mapping = aes(x0 = CV1.mean, y0 = CV2.mean, r = popn.radii),
              linetype = "dashed", 
              inherit.aes = FALSE) 

cva.plot2
```

###WIP

```{r}
library(Morpho)

## all examples are kindly provided by Marta Rufino

if (require(shapes)) {
# perform procrustes fit on raw data
alldat<-procSym(abind(gorf.dat,gorm.dat))

# create factors
groups<-as.factor(c(rep("female",30),rep("male",29)))

# perform CVA and test Mahalanobis distance
# between groups with permutation test by 100 rounds)            
cvall<-CVA(alldat$orpdata,groups,rounds=10000)     

## visualize a shape change from score -5 to 5:
cvvis5 <- 5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm
cvvisNeg5 <- -5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm
plot(cvvis5,asp=1)
points(cvvisNeg5,col=2)
for (i in 1:nrow(cvvisNeg5))
  lines(rbind(cvvis5[i,],cvvisNeg5[i,]))
}

### Morpho CVA
data(iris)
vari <- iris[,1:4]
facto <- iris[,5]

cva.1=CVA(vari, groups=facto)

## get the typicality probabilities and resulting classifications - tagging
## all specimens with a probability of < 0.01 as outliers (assigned to no class)
typprobs <- typprobClass(cva.1$CVscores,groups=facto)
print(typprobs)

## visualize the CV scores by their groups estimated from (cross-validated)
## typicality probabilities:
if (require(car)) {
scatterplot(cva.1$CVscores[,1],cva.1$CVscores[,2],groups=typprobs$groupaffinCV,
                  smooth=FALSE,reg.line=FALSE)
}

# plot the CVA
plot(cva.1$CVscores, col=facto, pch=as.numeric(facto), typ="n",asp=1,
   xlab=paste("1st canonical axis", paste(round(cva.1$Var[1,2],1),"%")),
   ylab=paste("2nd canonical axis", paste(round(cva.1$Var[2,2],1),"%")))
  
  text(cva.1$CVscores, as.character(facto), col=as.numeric(facto), cex=.7)

  # add chull (merge groups)
  for(jj in 1:length(levels(facto))){
        ii=levels(facto)[jj]
    kk=chull(cva.1$CVscores[facto==ii,1:2])
    lines(cva.1$CVscores[facto==ii,1][c(kk, kk[1])],
    cva.1$CVscores[facto==ii,2][c(kk, kk[1])], col=jj)
    }

  # add 80% ellipses
  if (require(car)) {
  for(ii in 1:length(levels(facto))){
    dataEllipse(cva.1$CVscores[facto==levels(facto)[ii],1],
    cva.1$CVscores[facto==levels(facto)[ii],2], 
                    add=TRUE,levels=.80, col=c(1:7)[ii])}
  }
  # histogram per group
  if (require(lattice)) {
  histogram(~cva.1$CVscores[,1]|facto,
  layout=c(1,length(levels(facto))),
          xlab=paste("1st canonical axis", paste(round(cva.1$Var[1,2],1),"%")))
  histogram(~cva.1$CVscores[,2]|facto, layout=c(1,length(levels(facto))),
          xlab=paste("2nd canonical axis", paste(round(cva.1$Var[2,2],1),"%")))
  } 
  # plot Mahalahobis
  dendroS=hclust(cva.1$Dist$GroupdistMaha)
  dendroS$labels=levels(facto)
  par(mar=c(4,4.5,1,1))
  dendroS=as.dendrogram(dendroS)
  plot(dendroS, main='',sub='', xlab="Geographic areas",
          ylab='Mahalahobis distance')

 
   # Variance explained by the canonical roots:
   cva.1$Var
   # or plot it:
   barplot(cva.1$Var[,2])

# another landmark based example in 3D: 
data(boneData)
groups <- name2factor(boneLM,which=3:4)
proc <- procSym(boneLM)
cvall<-CVA(proc$orpdata,groups)    

#' ## visualize a shape change from score -5 to 5:
cvvis5 <- 5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm
cvvisNeg5 <- -5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm

## Not run: 
#visualize it
deformGrid3d(cvvis5,cvvisNeg5,ngrid = 0)

## End(Not run)

#for using (e.g. the first 5) PCscores, one will do:
cvall <- CVA(proc$PCscores[,1:5],groups)    
#' ## visualize a shape change from score -5 to 5:
cvvis5 <- 5*cvall$CVvis[,1]+cvall$Grandm
cvvisNeg5 <- -5*cvall$CVvis[,1]+cvall$Grandm
cvvis5 <- restoreShapes(cvvis5,proc$PCs[,1:5],proc$mshape)
cvvisNeg5 <- restoreShapes(cvvisNeg5,proc$PCs[,1:5],proc$mshape)
## Not run: 
#visualize it
deformGrid3d(cvvis5,cvvisNeg5,ngrid = 0)

## End(Not run)
```

```{r}
library(Morpho)
library(car)
library(shapes)


lm_data <- read.csv("data/LM_Data.csv")
lm_data <- lm_data[,-1]

## all examples are kindly provided by Marta Rufino

#if (require(shapes)) {
# perform procrustes fit on raw data
#alldat <-procSym(abind(gorf.dat,gorm.dat))

# create factors
#groups <- as.factor(lm_data$Genus)


#perform CVA and test Mahalanobis distance
# between groups with permutation test by 100 rounds)            
#cvall<-CVA(alldat$orpdata, groups,rounds=10000)     

## visualize a shape change from score -5 to 5:
#cvvis5 <- 5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm
#cvvisNeg5 <- -5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm
#plot(cvvis5,asp=1)
#points(cvvisNeg5,col=2)
#for (i in 1:nrow(cvvisNeg5))
 # lines(rbind(cvvis5[i,],cvvisNeg5[i,]))
#}

### Morpho CVA
vari <- lm_data[,2:19]
#facto <- iris[,5]
facto <- as.factor(lm_data$Genus)
catalog <- as.factor(lm_data$catalogNumber)


cva.1 <- CVA(vari, groups=facto)

## get the typicality probabilities and resulting classifications - tagging
## all specimens with a probability of < 0.01 as outliers (assigned to no class)
typprobs <- typprobClass(cva.1$CVscores,groups=facto)
print(typprobs)

## visualize the CV scores by their groups estimated from (cross-validated)
## typicality probabilities:
if (require(car)) {
scatterplot(cva.1$CVscores[,1],cva.1$CVscores[,2],groups=typprobs$groupaffinCV,
                  smooth=FALSE,reg.line=FALSE)
}

# plot the CVA
plot(cva.1$CVscores, col=facto, pch=as.numeric(facto), typ="n",asp=1,
   xlab=paste("1st canonical axis", paste(round(cva.1$Var[1,2],1),"%")),
   ylab=paste("2nd canonical axis", paste(round(cva.1$Var[2,2],1),"%")))
  
  text(cva.1$CVscores, col=as.numeric(facto), cex=.7)
#  text(cva.1$CVscores, as.character(catalog), col=as.numeric(facto), cex=.7)

  
  
  # add chull (merge groups)
  for(jj in 1:length(levels(facto))){
        ii=levels(facto)[jj]
    kk=chull(cva.1$CVscores[facto==ii,1:2])
    lines(cva.1$CVscores[facto==ii,1][c(kk, kk[1])],
    cva.1$CVscores[facto==ii,2][c(kk, kk[1])], col=jj)
    }

  # add 80% ellipses
  if (require(car)) {
  for(ii in 1:length(levels(facto))){
    dataEllipse(cva.1$CVscores[facto==levels(facto)[ii],1],
    cva.1$CVscores[facto==levels(facto)[ii],2], 
                    add=TRUE,levels=.80, col=c(1:7)[ii])}
  }
```
```{r}
plot(cva.1$CVscores,
     col = as.numeric(facto),#color
     pch = as.numeric(facto), #symbol
     type = "n",
     asp = 1,
     xlab = paste("1st canonical axis", round(cva.1$Var[1,2],1), "%"),
     ylab = paste("2nd canonical axis", round(cva.1$Var[2,2],1), "%"))

points(cva.1$CVscores,
       col = as.numeric(facto),#color
       pch = as.numeric(facto),#symbols
       cex = 1) #point size

legend("topright",
       inset = c(0, 0),
       legend = levels(facto),
       col = seq_along(levels(facto)),
       pch = 19,
       cex = 0.75,
       bty = "n")

text(cva.1$CVscores,
     labels = as.character(catalog),
     col = as.numeric(facto),
     cex = 0.2)

```

#FINAL CVA
```{r}
grp <- levels(facto)
cols <- seq_along(grp)
pchs <- seq_along(grp)

plot(cva.1$CVscores,
     col = as.numeric(facto),#color
     pch = as.numeric(facto), #symbol
     type = "n",
     asp = 1,
     xlab = paste("1st canonical axis", round(cva.1$Var[1,2],1), "%"),
     ylab = paste("2nd canonical axis", round(cva.1$Var[2,2],1), "%"))

points(cva.1$CVscores,
       col = as.numeric(facto),#color
       pch = as.numeric(facto),#symbols
       cex = 0.6) #point size

legend("topright",
       inset = c(0, 0),
       legend = grp,
       col = cols,
       pch = pchs,
       cex = 0.75,
       bty = "n")

#text(cva.1$CVscores,
#     labels = as.character(catalog),
#     col = as.numeric(facto),
#     cex = 0.2)


```

```{r}

plot(cva.1$CVscores,
     col = as.numeric(facto),
     pch = as.numeric(facto),
     asp = 1,
     xlab = paste("1st canonical axis", round(cva.1$Var[1,2],1), "%"),
     ylab = paste("2nd canonical axis", round(cva.1$Var[2,2],1), "%"))

```
















```{r}
library(Morpho)
library(car)
library(shapes)


lm_data <- read.csv("data/LM_Data.csv")
lm_data <- lm_data[,-1]

### Morpho CVA
vari <- lm_data[,2:19]
#facto <- iris[,5]
facto <- as.factor(lm_data$Genus)
catalog <- as.factor(lm_data$catalogNumber)


cva.1=CVA(vari, groups=facto)

## get the typicality probabilities and resulting classifications - tagging
## all specimens with a probability of < 0.01 as outliers (assigned to no class)
typprobs <- typprobClass(cva.1$CVscores,groups=facto)
print(typprobs)

?typprobClass

## visualize the CV scores by their groups estimated from (cross-validated)
## typicality probabilities:
scatterplot(cva.1$CVscores[,1],cva.1$CVscores[,2],groups=typprobs$groupaffinCV,
                  smooth=FALSE,reg.line=FALSE)

```













```{r}
# histogram per group
  if (require(lattice)) {
  histogram(~cva.1$CVscores[,1]|facto,
  layout=c(1,length(levels(facto))),
          xlab=paste("1st canonical axis", paste(round(cva.1$Var[1,2],1),"%")))
  histogram(~cva.1$CVscores[,2]|facto, layout=c(1,length(levels(facto))),
          xlab=paste("2nd canonical axis", paste(round(cva.1$Var[2,2],1),"%")))
  }
```


```{r}
# plot Mahalahobis
  dendroS=hclust(cva.1$Dist$GroupdistMaha)
  dendroS$labels=levels(facto)
  par(mar=c(4,4.5,1,1))
  dendroS=as.dendrogram(dendroS)
  plot(dendroS, main='',sub='', cex=0.5, xlab="Genus",
          ylab='Mahalahobis distance')
  
```

```{r}
MahaDist <- as.data.frame(cva.1[["Dist"]][["GroupdistMaha"]])


MahaMatrix <- cva.1[["Dist"]][["GroupdistMaha"]]


cva.1[["Dist"]][["GroupdistMaha"]]

MahaMatrix
```

```{r}
library(phangorn)
library(ggtree)

# Plot the Neighbor-Joining tree (unrooted by default)
nj_tree <- nj(MahaMatrix)
ggtree(nj_tree,branch.length="branch.length", cex = 0.75) + geom_tiplab(size = 2) 


# Build a rooted tree using UPGMA (from 'phangorn' package)
upgma_tree <- upgma(MahaMatrix)
ggtree(upgma_tree,branch.length="branch.length", cex = 0.75) + geom_tiplab(size = 2) 

```




```{r}
# Variance explained by the canonical roots:
   cva.1$Var
# or plot it:
   barplot(cva.1$Var[,2])
   

?CVA()
   
CVscores <- cva.1$CVscores

mahadist <- cva.1$Dist$GroupdistMaha

mahadist2 <- as.numeric(mahadist)

CVmatrix <- cva.1$CV

LMmeans <- cva.1$groupmeans

```


###ITD DATA

```{r}
lm_data <- read.csv("data/LM_Data.csv")
lm_data <- lm_data[,-1]

### Morpho CVA
vari <- lm_data[,2:19]
#facto <- iris[,5]
facto <- as.factor(lm_data$Genus)
catalog <- as.factor(lm_data$catalogNumber)

levels(catalog)

cva.1 <- CVA(vari, groups=facto)

?CVA()

CVscores <- cva.1$CVscores

row.names(CVscores)

CVscores2 <- CVscores

row.names(CVscores2) <- lm_data$catalogNumber


metadata <- lm_data[,-c(2:19)]

library(dplyr)

CV_data_full <- cbind(CVscores, metadata)

```


### Phylogenetic Signal in Morphometric Data
Test for phylogenetic signal in the 
morphometric data using methods like Blomberg’s K or Pagel’s λ.

```{r}
library(phytools)


# Calculate Pagel’s λ (phylosig - phytools)
lambda_result <- phylosig(pruned_tree, LMmeans, method = "lambda", test = TRUE)
print(lambda_result)

# Calculate Blomberg's K
K_result <- phylosig(pruned_tree, LMmeans, method = "K", test = TRUE)
print(K_result)
```

### Phylogenetic Signal in Morphometric Data
Test for phylogenetic signal in the 
morphometric data using methods like Blomberg’s K or Pagel’s λ.

```{r}
library(phytools)
CV_Data <- read.csv("data/CV_Data.csv") 
row.names(CV_Data)
row.names(CV_Data) <- CV_Data$Genus
CV_Data$Genus <- NULL # Remove species column 'X'

CV_phylo <- as.matrix(CV_Data)

# Calculate Pagel’s λ (phylosig - phytools)
lambda_result <- phylosig(pruned_tree, CV_phylo, method = "lambda", test = TRUE)
print(lambda_result)

# Calculate Blomberg's K
K_result <- phylosig(pruned_tree, CV_phylo, method = "K", test = TRUE)
print(K_result)
```




```{r}
#' ## visualize a shape change from score -5 to 5:
cvvis5 <- 5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm
cvvisNeg5 <- -5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm


#for using (e.g. the first 5) PCscores, one will do:
cvall <- CVA(proc$PCscores[,1:5],groups)    


#' ## visualize a shape change from score -5 to 5:
cvvis5 <- 5*cvall$CVvis[,1]+cvall$Grandm
cvvisNeg5 <- -5*cvall$CVvis[,1]+cvall$Grandm
cvvis5 <- restoreShapes(cvvis5,proc$PCs[,1:5],proc$mshape)
cvvisNeg5 <- restoreShapes(cvvisNeg5,proc$PCs[,1:5],proc$mshape)

## Not run: 
#visualize it

## End(Not run)
```

###Calculate mean LM values
```{r}
### SUBSET
#Mean LM values by genus to calculate phylogenetic signal
mean_lmx1 <- aggregate(LM1x ~ Genus, data = subset_LM, FUN = mean)
mean_lmx2 <- aggregate(LM2x ~ Genus, data = subset_LM, FUN = mean)
mean_lmx3 <- aggregate(LM3x ~ Genus, data = subset_LM, FUN = mean)
mean_lmx4 <- aggregate(LM4x ~ Genus, data = subset_LM, FUN = mean)
mean_lmx5 <- aggregate(LM5x ~ Genus, data = subset_LM, FUN = mean)
mean_lmx6 <- aggregate(LM6x ~ Genus, data = subset_LM, FUN = mean)
mean_lmx7 <- aggregate(LM7x ~ Genus, data = subset_LM, FUN = mean)
mean_lmx8 <- aggregate(LM8x ~ Genus, data = subset_LM, FUN = mean)
mean_lmx9 <- aggregate(LM9x ~ Genus, data = subset_LM, FUN = mean)

mean_lmy1 <- aggregate(LM1y ~ Genus, data = subset_LM, FUN = mean)
mean_lmy2 <- aggregate(LM2y ~ Genus, data = subset_LM, FUN = mean)
mean_lmy3 <- aggregate(LM3y ~ Genus, data = subset_LM, FUN = mean)
mean_lmy4 <- aggregate(LM4y ~ Genus, data = subset_LM, FUN = mean)
mean_lmy5 <- aggregate(LM5y ~ Genus, data = subset_LM, FUN = mean)
mean_lmy6 <- aggregate(LM6y ~ Genus, data = subset_LM, FUN = mean)
mean_lmy7 <- aggregate(LM7y ~ Genus, data = subset_LM, FUN = mean)
mean_lmy8 <- aggregate(LM8y ~ Genus, data = subset_LM, FUN = mean)
mean_lmy9 <- aggregate(LM9y ~ Genus, data = subset_LM, FUN = mean)

#mean_lmx3, mean_lmx4, mean_lmx5, mean_lmx6, mean_lmx7, mean_lmx8, mean_lmx9, mean_lmy1, mean_lmy2, mean_lmy3, mean_lmy4, mean_lmy5, mean_lmy6, mean_lmy7, mean_lmy8, mean_lmy9

mean_LM2 <- merge(mean_lmx1, mean_lmx2, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmx3, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmx4, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmx5, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmx6, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmx7, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmx8, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmx9, by=c("Genus"))

mean_LM2 <- merge(mean_LM2, mean_lmy1, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmy2, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmy3, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmy4, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmy5, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmy6, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmy7, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmy8, by=c("Genus"))
mean_LM2 <- merge(mean_LM2, mean_lmy9, by=c("Genus"))

rownames(mean_LM2) <- mean_LM2$Genus

mean_LM3 <- mean_LM2[, -1] 

LM_matrix_subset <- mean_LM3

write.csv(LM_matrix_subset, file = "data/GM_Data_subset.csv")

```


```{r}
## all examples are kindly provided by Marta Rufino

if (require(shapes)) {
# perform procrustes fit on raw data
alldat<-procSym(abind(gorf.dat,gorm.dat))
# create factors
groups<-as.factor(c(rep("female",30),rep("male",29)))
# perform CVA and test Mahalanobis distance
# between groups with permutation test by 100 rounds)            
cvall<-CVA(alldat$orpdata,groups,rounds=10000)     
## visualize a shape change from score -5 to 5:
cvvis5 <- 5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm
cvvisNeg5 <- -5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm
plot(cvvis5,asp=1)
points(cvvisNeg5,col=2)
for (i in 1:nrow(cvvisNeg5))
  lines(rbind(cvvis5[i,],cvvisNeg5[i,]))
}
```


```{r}
### Morpho CVA
data(iris)
vari <- iris[,1:4]
facto <- iris[,5]

cva.1=CVA(vari, groups=facto)
## get the typicality probabilities and resulting classifications - tagging
## all specimens with a probability of < 0.01 as outliers (assigned to no class)
typprobs <- typprobClass(cva.1$CVscores,groups=facto)
print(typprobs)
## visualize the CV scores by their groups estimated from (cross-validated)
## typicality probabilities:
if (require(car)) {
scatterplot(cva.1$CVscores[,1],cva.1$CVscores[,2],groups=typprobs$groupaffinCV,
                  smooth=FALSE,reg.line=FALSE)
}
# plot the CVA
plot(cva.1$CVscores, col=facto, pch=as.numeric(facto), typ="n",asp=1,
   xlab=paste("1st canonical axis", paste(round(cva.1$Var[1,2],1),"%")),
   ylab=paste("2nd canonical axis", paste(round(cva.1$Var[2,2],1),"%")))
  
  text(cva.1$CVscores, as.character(facto), col=as.numeric(facto), cex=.7)

  # add chull (merge groups)
  for(jj in 1:length(levels(facto))){
        ii=levels(facto)[jj]
    kk=chull(cva.1$CVscores[facto==ii,1:2])
    lines(cva.1$CVscores[facto==ii,1][c(kk, kk[1])],
    cva.1$CVscores[facto==ii,2][c(kk, kk[1])], col=jj)
    }

  # add 80% ellipses
  if (require(car)) {
  for(ii in 1:length(levels(facto))){
    dataEllipse(cva.1$CVscores[facto==levels(facto)[ii],1],
    cva.1$CVscores[facto==levels(facto)[ii],2], 
                    add=TRUE,levels=.80, col=c(1:7)[ii])}
  }
  # histogram per group
  if (require(lattice)) {
  histogram(~cva.1$CVscores[,1]|facto,
  layout=c(1,length(levels(facto))),
          xlab=paste("1st canonical axis", paste(round(cva.1$Var[1,2],1),"%")))
  histogram(~cva.1$CVscores[,2]|facto, layout=c(1,length(levels(facto))),
          xlab=paste("2nd canonical axis", paste(round(cva.1$Var[2,2],1),"%")))
  } 
  # plot Mahalahobis
  dendroS=hclust(cva.1$Dist$GroupdistMaha)
  dendroS$labels=levels(facto)
  par(mar=c(4,4.5,1,1))
  dendroS=as.dendrogram(dendroS)
  plot(dendroS, main='',sub='', xlab="Geographic areas",
          ylab='Mahalahobis distance')

 
   # Variance explained by the canonical roots:
   cva.1$Var
   # or plot it:
   barplot(cva.1$Var[,2])

# another landmark based example in 3D: 
data(boneData)
groups <- name2factor(boneLM,which=3:4)
proc <- procSym(boneLM)
cvall<-CVA(proc$orpdata,groups)    
#' ## visualize a shape change from score -5 to 5:
cvvis5 <- 5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm
cvvisNeg5 <- -5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm
## Not run: 
#visualize it
deformGrid3d(cvvis5,cvvisNeg5,ngrid = 0)

## End(Not run)

#for using (e.g. the first 5) PCscores, one will do:
cvall <- CVA(proc$PCscores[,1:5],groups)    
#' ## visualize a shape change from score -5 to 5:
cvvis5 <- 5*cvall$CVvis[,1]+cvall$Grandm
cvvisNeg5 <- -5*cvall$CVvis[,1]+cvall$Grandm
cvvis5 <- restoreShapes(cvvis5,proc$PCs[,1:5],proc$mshape)
cvvisNeg5 <- restoreShapes(cvvisNeg5,proc$PCs[,1:5],proc$mshape)
## Not run: 
#visualize it
deformGrid3d(cvvis5,cvvisNeg5,ngrid = 0)

## End(Not run)
```

```{r}

## all examples are kindly provided by Marta Rufino

if (require(shapes)) {
# perform procrustes fit on raw data
alldat<-procSym(abind(gorf.dat,gorm.dat))
# create factors
groups<-as.factor(c(rep("female",30),rep("male",29)))
# perform CVA and test Mahalanobis distance
# between groups with permutation test by 100 rounds)            
cvall<-CVA(alldat$orpdata,groups,rounds=10000)     
## visualize a shape change from score -5 to 5:
cvvis5 <- 5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm
cvvisNeg5 <- -5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm
plot(cvvis5,asp=1)
points(cvvisNeg5,col=2)
for (i in 1:nrow(cvvisNeg5))
  lines(rbind(cvvis5[i,],cvvisNeg5[i,]))
}
### Morpho CVA
data(iris)
vari <- iris[,1:4]
facto <- iris[,5]

cva.1=CVA(vari, groups=facto, rounds = 1000)
## get the typicality probabilities and resulting classifications - tagging
## all specimens with a probability of < 0.01 as outliers (assigned to no class)
typprobs <- typprobClass(cva.1$CVscores,groups=facto)
print(typprobs)
## visualize the CV scores by their groups estimated from (cross-validated)
## typicality probabilities:
if (require(car)) {
scatterplot(cva.1$CVscores[,1],cva.1$CVscores[,2],groups=typprobs$groupaffinCV,
                  smooth=FALSE,reg.line=FALSE)
}
# plot the CVA
plot(cva.1$CVscores, col=facto, pch=as.numeric(facto), typ="n",asp=1,
   xlab=paste("1st canonical axis", paste(round(cva.1$Var[1,2],1),"%")),
   ylab=paste("2nd canonical axis", paste(round(cva.1$Var[2,2],1),"%")))
  
  text(cva.1$CVscores, as.character(facto), col=as.numeric(facto), cex=.7)

  # add chull (merge groups)
  for(jj in 1:length(levels(facto))){
        ii=levels(facto)[jj]
    kk=chull(cva.1$CVscores[facto==ii,1:2])
    lines(cva.1$CVscores[facto==ii,1][c(kk, kk[1])],
    cva.1$CVscores[facto==ii,2][c(kk, kk[1])], col=jj)
    }

  # add 80% ellipses
  if (require(car)) {
  for(ii in 1:length(levels(facto))){
    dataEllipse(cva.1$CVscores[facto==levels(facto)[ii],1],
    cva.1$CVscores[facto==levels(facto)[ii],2], 
                    add=TRUE,levels=.80, col=c(1:7)[ii])}
  }
  # histogram per group
  if (require(lattice)) {
  histogram(~cva.1$CVscores[,1]|facto,
  layout=c(1,length(levels(facto))),
          xlab=paste("1st canonical axis", paste(round(cva.1$Var[1,2],1),"%")))
  histogram(~cva.1$CVscores[,2]|facto, layout=c(1,length(levels(facto))),
          xlab=paste("2nd canonical axis", paste(round(cva.1$Var[2,2],1),"%")))
  } 
  # plot Mahalahobis
  dendroS=hclust(cva.1$Dist$GroupdistMaha)
  dendroS$labels=levels(facto)
  par(mar=c(4,4.5,1,1))
  dendroS=as.dendrogram(dendroS)
  plot(dendroS, main='',sub='', xlab="Geographic areas",
          ylab='Mahalahobis distance')

 
   # Variance explained by the canonical roots:
   cva.1$Var
   # or plot it:
   barplot(cva.1$Var[,2])

# another landmark based example in 3D: 
data(boneData)
groups <- name2factor(boneLM,which=3:4)
proc <- procSym(boneLM)
cvall<-CVA(proc$orpdata,groups)    
#' ## visualize a shape change from score -5 to 5:
cvvis5 <- 5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm
cvvisNeg5 <- -5*matrix(cvall$CVvis[,1],nrow(cvall$Grandm),ncol(cvall$Grandm))+cvall$Grandm
## Not run: 
#visualize it
deformGrid3d(cvvis5,cvvisNeg5,ngrid = 0)

## End(Not run)

#for using (e.g. the first 5) PCscores, one will do:
cvall <- CVA(proc$PCscores[,1:5],groups)    
#' ## visualize a shape change from score -5 to 5:
cvvis5 <- 5*cvall$CVvis[,1]+cvall$Grandm
cvvisNeg5 <- -5*cvall$CVvis[,1]+cvall$Grandm
cvvis5 <- restoreShapes(cvvis5,proc$PCs[,1:5],proc$mshape)
cvvisNeg5 <- restoreShapes(cvvisNeg5,proc$PCs[,1:5],proc$mshape)
## Not run: 
#visualize it
deformGrid3d(cvvis5,cvvisNeg5,ngrid = 0)

## End(Not run)


?predict.CVA


cva.1
```


```{r}
library(Quartet)
library(ape)

# Example trees
set.seed(1)

tree1 <- ref_tree
tree2 <- nj_tree

# Observed quartet similarity
qs_obs <- QuartetStatus(ref_tree, nj_tree)

# Example similarity metric
obs <- SimilarityMetrics(qs_obs)[,"ExplicitlyAgree"]

obs

nperm <- 999

perm_stats <- numeric(nperm)

for(i in 1:nperm){

  # permute taxa labels of tree2
  perm_tree <- nj_tree
  perm_tree$tip.label <- sample(perm_tree$tip.label)

  # quartet comparison
  qs_perm <- QuartetStatus(ref_tree, perm_tree)

  # similarity statistic
  perm_stats[i] <- SimilarityMetrics(qs_perm)[,"ExplicitlyAgree"]
}

pval <- (sum(perm_stats >= obs) + 1) / (nperm + 1)

pval
```

```{r}
library(Quartet)
library(ape)

# Example trees
set.seed(1)

tree1 <- ref_tree
#tree2 <- nj_tree
tree2 <- upgma_tree

# Observed quartet similarity
qs_obs <- QuartetStatus(ref_tree, upgma_tree)

# Example similarity metric
obs <- SimilarityMetrics(qs_obs)[,"ExplicitlyAgree"]

obs

nperm <- 999

perm_stats <- numeric(nperm)

for(i in 1:nperm){

  # permute taxa labels of tree2
  perm_tree <- upgma_tree
  perm_tree$tip.label <- sample(perm_tree$tip.label)

  # quartet comparison
  qs_perm <- QuartetStatus(ref_tree, perm_tree)

  # similarity statistic
  perm_stats[i] <- SimilarityMetrics(qs_perm)[,"ExplicitlyAgree"]
}

pval <- (sum(perm_stats >= obs) + 1) / (nperm + 1)

pval
```

```{r}
library(Quartet)
library(ape)

# Example trees
set.seed(1)

tree1 <- rtree(20)
tree2 <- rtree(20)

# Observed quartet similarity
qs_obs <- QuartetStatus(tree1, tree2)

# Example similarity metric
obs <- SimilarityMetrics(qs_obs)[,"ExplicitlyAgree"]

obs

nperm <- 999

perm_stats <- numeric(nperm)

for(i in 1:nperm){

  # permute taxa labels of tree2
  perm_tree <- tree2
  perm_tree$tip.label <- sample(perm_tree$tip.label)

  # quartet comparison
  qs_perm <- QuartetStatus(tree1, perm_tree)

  # similarity statistic
  perm_stats[i] <- SimilarityMetrics(qs_perm)[,"ExplicitlyAgree"]
}

pval <- (sum(perm_stats >= obs) + 1) / (nperm + 1)

pval
```

```{r}
library(Quartet)
library(ape)

# Example trees

ref_tree
nj_tree
upgma_tree

tree1 <- ref_tree
tree1 <- upgma_tree
tree2 <- nj_tree

# Observed quartet similarity
qs_obs <- QuartetStatus(tree1, tree2)

# Example similarity metric
obs <- SimilarityMetrics(qs_obs)[,"ExplicitlyAgree"]

obs

nperm <- 999

perm_stats <- numeric(nperm)

for(i in 1:nperm){

  # permute taxa labels of tree2
  perm_tree <- tree2
  perm_tree$tip.label <- sample(perm_tree$tip.label)

  # quartet comparison
  qs_perm <- QuartetStatus(tree1, perm_tree)

  # similarity statistic
  perm_stats[i] <- SimilarityMetrics(qs_perm)[,"ExplicitlyAgree"]
}

pval <- (sum(perm_stats >= obs) + 1) / (nperm + 1)

pval
```








